/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.soofaloofa.taskmanager;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class taskmanagerConstants {

  /**
   * Define a constant using the `const` keyword.
   */
  public static final long DEFAULT_ID = -1L;

}
